declare var md: any
declare var markdownitSynapse: any
declare var markdownSubAlt: any
declare var markdownCenterText: any
declare var markdownSynapseHeading: any
declare var markdownSynapseTable: any
declare var markdownStrikethrough: any
declare var markdownContainer: any
declare var markdownEmpahsisAlt: any
declare var markdownInlineComments: any
declare var markdownBr: any
declare var sanitizeHtml: any
declare var synapseMath: any
